name: chari_spot
description: 駐車場マップUI

publish_to: 'none' # プロジェクトを pub.dev に公開しない場合はこのままでOK

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  http: ^1.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/